### ISSUE TITLE
Question: Is this extension still being worked on?

### ISSUE THREAD

**Issue by borgdylan** [Microsoft/vscode-mono-debug#13]
Is this extension being brought up to date with the newer VS Code releases?

**Comment by weinand** [comment]
@borgdylan I'll try my best to keep this extension in sync with the latest VS Code. But since mono-debug delegates most functionality to the underlying SDB command line debugger (which does not seem to be actively developed any more), I'm limited in what I can fix and what new features I can implement (but I'm accepting pull requests ;-)
 
(This extension was basically a 2 day hackathon 'proof of concept' of the VS Code debugger protocol. It was never intended to become 'The Mono Debugger'.)

**Comment by borgdylan** [comment]
I hope that someone that is experienced with mono, will come up with a variant that uses Mono.Debugger.Soft directly and take the pressure off of this extension then.
